import Foundation

/// Utility class for parsing and serializing macOS /etc/hosts file format.
enum HostsFileParser {

    /// Parses raw contents of a hosts file into an array of HostEntry models.
    static func parse(content: String) -> [HostEntry] {
        var entries: [HostEntry] = []
        let lines = content.components(separatedBy: .newlines)
        
        var currentCategory = "General"

        for line in lines {
            let trimmed = line.trimmingCharacters(in: .whitespaces)
            if trimmed.isEmpty { continue }

            // Header comment indicating category section, e.g. "### Local Development"
            if trimmed.hasPrefix("###") {
                let categoryName = trimmed.replacingOccurrences(of: "#", with: "").trimmingCharacters(in: .whitespaces)
                if !categoryName.isEmpty {
                    currentCategory = categoryName
                }
                continue
            }

            // Check if line is commented out (might be a disabled entry or pure comment)
            var isCommentedOut = false
            var workLine = trimmed

            if workLine.hasPrefix("#") {
                isCommentedOut = true
                // Strip the leading '#' and whitespace
                workLine = String(workLine.dropFirst()).trimmingCharacters(in: .whitespaces)
            }

            // Split line into host definition and inline comment
            var inlineComment = ""
            if let commentIndex = workLine.firstIndex(of: "#") {
                inlineComment = String(workLine[workLine.index(after: commentIndex)...]).trimmingCharacters(in: .whitespaces)
                workLine = String(workLine[..<commentIndex]).trimmingCharacters(in: .whitespaces)
            }

            // Split into components (IP + Hostnames)
            let parts = workLine.components(separatedBy: .whitespaces).filter { !$0.isEmpty }

            // We need at least an IP and one hostname to be a valid entry
            if parts.count >= 2, isIPAddress(parts[0]) {
                let ip = parts[0]
                let isSystemEntry = isSystemHost(ip: ip, hostnames: Array(parts.dropFirst()))

                for hostname in parts.dropFirst() {
                    let entry = HostEntry(
                        ipAddress: ip,
                        hostname: hostname,
                        comment: inlineComment,
                        isEnabled: !isCommentedOut,
                        isSystem: isSystemEntry,
                        category: isSystemEntry ? "System" : currentCategory
                    )
                    entries.append(entry)
                }
            } else if isCommentedOut && parts.count >= 2 && isIPAddress(parts[0]) {
                // Disabled host entry parsing
                let ip = parts[0]
                let isSystemEntry = isSystemHost(ip: ip, hostnames: Array(parts.dropFirst()))
                for hostname in parts.dropFirst() {
                    let entry = HostEntry(
                        ipAddress: ip,
                        hostname: hostname,
                        comment: inlineComment,
                        isEnabled: false,
                        isSystem: isSystemEntry,
                        category: isSystemEntry ? "System" : currentCategory
                    )
                    entries.append(entry)
                }
            }
        }

        return entries
    }

    /// Serializes array of HostEntry items back into standard /etc/hosts formatted string.
    static func generateHostsContent(from entries: [HostEntry]) -> String {
        var output = """
        ##
        # Host Database
        #
        # localhost is used to configure the loopback interface
        # when the system is booting.  Do not change this entry.
        #
        # Generated by SwiftHosts on \(DateFormatter.localizedString(from: Date(), dateStyle: .medium, timeStyle: .medium))
        ##

        """

        // Group entries by category
        let categories = Dictionary(grouping: entries, by: { $0.category })
        
        // System entries first
        if let systemEntries = categories["System"] {
            output += "### System Entries\n"
            for entry in systemEntries {
                output += formatLine(for: entry) + "\n"
            }
            output += "\n"
        }

        // Other categories
        let remainingCategories = categories.keys.filter { $0 != "System" }.sorted()
        for cat in remainingCategories {
            guard let catEntries = categories[cat], !catEntries.isEmpty else { continue }
            output += "### \(cat)\n"
            for entry in catEntries {
                output += formatLine(for: entry) + "\n"
            }
            output += "\n"
        }

        return output
    }

    private static func formatLine(for entry: HostEntry) -> String {
        let paddingLength = max(16 - entry.ipAddress.count, 1)
        let spacing = String(repeating: " ", count: paddingLength)
        var line = "\(entry.ipAddress)\(spacing)\(entry.hostname)"
        
        if !entry.comment.isEmpty {
            line += " # \(entry.comment)"
        }

        if !entry.isEnabled {
            line = "# \(line)"
        }

        return line
    }

    private static func isIPAddress(_ string: String) -> Bool {
        var sin = sockaddr_in()
        var sin6 = sockaddr_in6()
        return inet_pton(AF_INET, string, &sin.sin_addr) == 1 || inet_pton(AF_INET6, string, &sin6.sin6_addr) == 1
    }

    private static func isSystemHost(ip: String, hostnames: [String]) -> Bool {
        let systemIPs = ["127.0.0.1", "255.255.255.255", "::1", "fe80::1%lo0"]
        let systemHosts = ["localhost", "broadcasthost", "local"]
        
        if systemIPs.contains(ip) {
            for name in hostnames {
                if systemHosts.contains(name.lowercased()) {
                    return true
                }
            }
        }
        return false
    }
}
